#!/bin/bash

a=(1 6 1 1 1 2 1)
b=(2 5 1 2 1 1 2)
c=(3 4 1 1 1 1 1)
d=(4 3 1 3 1 1 1)
e=(5 2 1 4 1 1 1)
f=(6 1 1 5 2 1 1)
result=(1 1 1 0 1 1 0)




for ind in $(seq 0 6)
do
out=$('./zad3.1' $1 ${a[$ind]} ${b[$ind]} ${c[$ind]} ${d[$ind]} ${e[$ind]} ${f[$ind]})
if [ "$out" != "${result[$ind]}" ]
then
echo "input" ${a[$ind]} ${b[$ind]} ${c[$ind]} ${d[$ind]} ${e[$ind]} ${f[$ind]}
echo "output actual" $out
echo "output expected" ${result[$ind]}
fi
done
